### ISSUE TITLE
Suggestion: Use RubaXa/Sortable

### ISSUE THREAD

**Issue by YasserHassan** [kartik-v/yii2-sortable#11]
Hi @kartik-v. The [RubaXa/Sortable](http://github.com/RubaXa/Sortable) library seems to be more widely used than `html5sortable` (compare GitHub's watches and stars) and provides more features like better support for touch devices and more features like auto-scroll. Using it instead of `html5sortable` could  provide a better sortable extension and enhance the dependent ones. I wonder if it is feasible to use it in your `yii2-sortable` extension (without breaking compatibility of course). I am willing to participate in that if you decide to do it.

**Comment by kartik-v** [comment]
Will check when I get time. The main purpose of using html5Sortable plugin was that it was a simple and lean plugin that gave most of the sortable features with a leaner code base.

**Comment by YasserHassan** [comment]
From what I've seen, RubaXa/Sortable seems to be also simple and lean but more powerful and more actively developed. It is not based on jQuery same as html5sortable. At the moment of this writing, Sortable has 4,860 stars vs. 458 for html5sortable (they both have almost the same age). I'll be waiting for your decision.
