### ISSUE TITLE
Method $this->isBs4() do not exist in Sortable.php

### ISSUE THREAD

**Issue by jjmaceda** [kartik-v/yii2-sortable#19]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-sortable.
- [x] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/sortable).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. composer update
2. Updating kartik-v/yii2-sortable dev-master (5d418b8 => 89593b9)
3. Calling unknown method: kartik\sortable\Sortable::isBs4()

## Expected behavior and actual behavior

When I follow those steps, I see...
Calling unknown method: kartik\sortable\Sortable::isBs4()
I was expecting...
loading the page normally
#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [x] Safari

#### Operating System

- [x] Windows
- [x] Mac OS X
- [x] Linux
- [x] Mobile

#### Libraries

- jQuery version: 
- yii2-sortable version:  dev-master

## Isolating the problem

- [ ] This bug happens [on the docs and demos page](https://demos.krajee.com/sortable)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-sortable without other plugins.

**Comment by kartik-v** [comment]
You must run `composer update` to update all extensions with their dependencies. 

The issue for you is happening because you do not have updated releases of all extensions and their dependencies OR you are trying to manually update / copy only this extension without dependency.
