### ISSUE TITLE
html5sortable.js: Object does not support 'assign'

### ISSUE THREAD

**Issue by Commifreak** [kartik-v/yii2-sortable#21]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-sortable.
- [x] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/sortable).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Expected behavior and actual behavior
On IE, I get this error:

```
html5sortable.js (756,9): This object does not support the property or method "assign" (translated from german).
```

Code snip:

```js
    function sortable(sortableElements, options) {
        // get method string to see if a method is called
        var method = String(options);
        // merge user options with defaultss
        options = Object.assign({
```

This leads to not functioning sortable in DynGrid config-page.

Any ideas whats wrong here?

On Yii 2.0.15.1 with jQuery 2.2.4

#### Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [x] Internet Explorer 11
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-sortable version: 1.2.2

**Comment by adamwinn** [comment]
I'm seeing this exact same issue too.  https://github.com/kartik-v/yii2-dynagrid/issues/214

**Comment by adamwinn** [comment]
Add the following polyfill and it should work:

https://cdn.polyfill.io/v2/polyfill.js?features=default,Object.entries,Array.prototype.includes

https://github.com/lukasoppermann/html5sortable/issues/445

**Comment by Commifreak** [comment]
That worked!

**Comment by kartik-v** [comment]
Thanks. Closing the issue.
