### ISSUE TITLE
Wrong documentation link?

### ISSUE THREAD

**Issue by bizley-code** [kartik-v/yii2-sortable#7]
Correct me if I'm wrong but it looks like you provide the link to the documentation for https://github.com/voidberg/html5sortable (here and at http://demos.krajee.com/sortable ) while this widget is based on https://github.com/farhadi/html5sortable (maybe earlier those two were almost identical but now Voidberg's is way ahead).
And I was wondering why 'sortstart' event doesn't work...

Are you planning to replace the js for this widget with newer version? If not maybe switch the documentation link ;)

**Comment by kartik-v** [comment]
No the docs are correct. The extension was updated to use voidberg's fork -- however it is not on the latest version of voidberg -- will need to do it when I get time - as it needs extensive testing.
